stages:
  - default
  - build-app

variables:
  POSTGRES_DB: "sgrap_db"
  POSTGRES_USER: "postgres"
  POSTGRES_PASSWORD: "postgres"
  PGDATA: "/var/lib/postgresql/data"
  POSTGRES_INITDB_ARGS: "--encoding=UTF8 --data-checksums"
  DATABASE_URL: "postgresql://postgres:postgres@localhost:5432/sgrap_db?schema=public"
  AUTH_SECRET: "j1fjpU7H9ozNamG4Nn2r1UDF7r4VzcuwSe3Ve6XtWac="
  DOMAIN_URL: "http://localhost:3000"

default:
  services:
    - node:20
    - postgres:16.2-alpine3.19
    - rnwood/smtp4dev:v3


build app:
  stage: build-app
  script:
    - npm
    - npm install
    - npx prisma db push
    - npm run lint
    - npm run build

  cache:
    paths:
      - node_modules
  artifacts:
    paths:
      - .next
      - build
    expire_in: 1 day