services:
  postgres:
    image: postgres:16.2-alpine3.19
    ports:
      - "5433:5432"
    container_name: sgrap-db
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=sgrap_db